provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: rdimitrov/helloworld:latest
#  qrcode-reader:
#    lang: python
#    handler: ./qrcode-reader
#    image: rdimitrov/qrcode-reader:latest
#    build_options:
#    - dev
  yell-dockerhub-image:
    lang: go
    handler: ./yell-dockerhub-image
    image: rdimitrov/yell-dockerhub-image:latest
