provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: rdimitrov/helloworld:latest
  helloworld-py:
    lang: python
    handler: ./helloworld-py
    image: rdimitrov/helloworld-py:latest
    build_options:
    - dev
  yell-dockerhub-image:
    lang: go
    handler: ./yell-dockerhub-image
    image: rdimitrov/yell-dockerhub-image:latest
